### ISSUE TITLE
Search button

### ISSUE THREAD

**Issue by wellkunnected** [sanjibahmad/Smashtag#1]
Great app! Only problem is, after entering your search query in the search bar there's no way to search or an "enter" button so your stuck on #stanford which is the app's default hashtag search. How can I add a search button to the UI? Thanks for the direction!

**Comment by sanjib** [comment]
Thanks for the comment. Perhaps your "Connect Hardware Keyboard" state is off in the Simulator which could be the reason you can't type and replace the default #stanford search query. Please try pressing shift-cmd-k in the Simulator to toggle the state. You should then be able type your queries and press enter to run the search.

**Comment by sanjib** [comment]
I didn't bother implementing a button as the ideal search solution should be a UISearchController instead of a UITextField. Besides if you run the app on a device a button would be redundant since you will have the iPhone keyboard slide up for assistance. You can also simulate the keyboard sliding up in the Simulator by pressing cmd-k equivalent to "Toggle Software Keyboard".

**Comment by sanjib** [comment]
Feel free to let me know if you succeeded in typing your search queries.

**Comment by wellkunnected** [comment]
Yea but the problem is I'm running this on my iPhone 6+ and I had to turn
my device sideways to find the hide keyboard toggle but even that only
hides the keyboard. If there is no physical "search" button I don't see a
way that a user would be able to implement the search function. The
"return" key isn't shown when running the app, but I used the cmd + shift +
k so I'll see if that helps. Thanks.

On Wed, Mar 23, 2016 at 11:47 AM, Sanjib Ahmad notifications@github.com
wrote:

> I didn't bother implementing a button as the ideal search solution should
> be a UISearchController instead of a UITextField. Besides if you run the
> app on a device a button would be redundant since you will have the iPhone
> keyboard slide up for assistance. You can also simulate the keyboard
> sliding up in the Simulator by pressing cmd-k equivalent to "Toggle
> Software Keyboard".
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/sanjibahmad/Smashtag/issues/1#issuecomment-200403155

## 

Founded Well Kunnected, Inc 2010

**Comment by wellkunnected** [comment]
Please see the attached screenshot. Even after following your instructions
and cleaning the build using cmd + shift + k no Return or search button is
present. How am I supposed to search the app when only the # and @ symbols
are present in the keyboard?

On Wed, Mar 23, 2016 at 11:55 AM, Armani Rouse armanirouse@gmail.com
wrote:

> Yea but the problem is I'm running this on my iPhone 6+ and I had to turn
> my device sideways to find the hide keyboard toggle but even that only
> hides the keyboard. If there is no physical "search" button I don't see a
> way that a user would be able to implement the search function. The
> "return" key isn't shown when running the app, but I used the cmd + shift +
> k so I'll see if that helps. Thanks.
> 
> On Wed, Mar 23, 2016 at 11:47 AM, Sanjib Ahmad notifications@github.com
> wrote:
> 
> > I didn't bother implementing a button as the ideal search solution should
> > be a UISearchController instead of a UITextField. Besides if you run the
> > app on a device a button would be redundant since you will have the iPhone
> > keyboard slide up for assistance. You can also simulate the keyboard
> > sliding up in the Simulator by pressing cmd-k equivalent to "Toggle
> > Software Keyboard".
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> > https://github.com/sanjibahmad/Smashtag/issues/1#issuecomment-200403155
> 
> ## 
> 
> Founded Well Kunnected, Inc 2010

## 

Founded Well Kunnected, Inc 2010

**Comment by sanjib** [comment]
Actually I was referring to CMD+SHIFT+K to be run on the Simulator, not in Xcode:

![connect-hardware-keyboard](https://cloud.githubusercontent.com/assets/3517218/13992880/fdd1e962-f147-11e5-8317-4a2cefa57882.png)

I was using the Twitter keyboard ![twitter-keyboard](https://cloud.githubusercontent.com/assets/3517218/13993282/ec71cea6-f149-11e5-8aca-143607db3334.png) (which sounded nice for the Twitter search) which unfortunately doesn't have a Return key. I have changed it to Default so, you should be able to see the Return key now on the iPhone keyboard:

![return-key-on-screen-keyboard](https://cloud.githubusercontent.com/assets/3517218/13993108/1eeee464-f149-11e5-967d-9b12c6566798.png)

**Comment by wellkunnected** [comment]
Ohhhhh :) How do i run this in simulator without using Xcode?

On Wed, Mar 23, 2016 at 12:54 PM, Sanjib Ahmad notifications@github.com
wrote:

> Actually I was referring to CMD+SHIFT+K to be run on the Simulator, not in
> Xcode:
> 
> [image: connect-hardware-keyboard]
> https://cloud.githubusercontent.com/assets/3517218/13992880/fdd1e962-f147-11e5-8317-4a2cefa57882.png
> 
> I was using the Twitter keyboard [image: twitter-keyboard]
> https://cloud.githubusercontent.com/assets/3517218/13993282/ec71cea6-f149-11e5-8aca-143607db3334.png
> (which sounded nice for the Twitter search) which unfortunately doesn't
> have a Return key. I have changed it to Default so, you should be able to
> see the Return key now on the iPhone keyboard:
> 
> [image: return-key-on-screen-keyboard]
> https://cloud.githubusercontent.com/assets/3517218/13993108/1eeee464-f149-11e5-967d-9b12c6566798.png
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/sanjibahmad/Smashtag/issues/1#issuecomment-200439263

## 

Founded Well Kunnected, Inc 2010

**Comment by sanjib** [comment]
I was trying to be explicit because in Xcode SHIFT+CMD+K will "Clean"; while in the Simulator it will toggle the state of "Connect Hardware Keyboard".
Anyway, thank you for the suggestion to add the Search button. I have added it now to both the Tweets table and collection view controller.

**Comment by wellkunnected** [comment]
So should I re download the ZIP file on github? And no problem! I love
checking out cool projects on Github and reporting back with any bugs or
issues to help the developers improve :)

On Wed, Mar 23, 2016 at 2:25 PM, Sanjib Ahmad notifications@github.com
wrote:

> I was trying to be explicit because in Xcode SHIFT+CMD+K will "Clean";
> while in the Simulator it will toggle the state of "Connect Hardware
> Keyboard".
> Anyway, thank you for the suggestion to add the Search button. I have
> added it now to both the Tweets table and collection view controller.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/sanjibahmad/Smashtag/issues/1#issuecomment-200481168

## 

Founded Well Kunnected, Inc 2010

**Comment by sanjib** [comment]
Yes please go ahead and download the ZIP file on Github.

**Comment by wellkunnected** [comment]
AWESOME WORK MY FRIEND THANK YOU SIR! :D It works beautifully now, I am very happy about this project, my colleagues like it as well! Thanks again Sanjib.

**Comment by sanjib** [comment]
My pleasure :) Thank you and have a great day!

**Comment by wellkunnected** [comment]
Likewise Sanjib :D

On Wed, Mar 23, 2016 at 3:00 PM, Sanjib Ahmad notifications@github.com
wrote:

> Closed #1 https://github.com/sanjibahmad/Smashtag/issues/1.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/sanjibahmad/Smashtag/issues/1#event-600768985

## 

Founded Well Kunnected, Inc 2010
